name: Continuous Integration

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Display python version
        run: python3 --version

      - name: Upgrade pip
        run: pip3 install --upgrade pip setuptools

      - name: Install dev dependencies
        run: pip3 install -r dev-requirements.txt

      - name: Install pyp5js for dev
        run: python3 setup.py develop --install-dir dist

      - name:
        run: pytest
